<?php
$page_name = 'Home Page';
$page_des = 'Team Leads';

$header_scripts = array();
$footer_scripts = array();

include_once WWW_DIR.'page/template.header.php';
include_once WWW_DIR.'page/template.nav.php';
?>

<!-- Page Content -->
<div id="page-wrapper">
	<div class="container-fluid">
		<div class="row">
			<div class="col-lg-12">
				<img src="/dist/img/404.jpg"/>
			</div>
			<!-- /.col-lg-12 -->
		</div>
		<!-- /.row -->
	</div>
	<!-- /.container-fluid -->
</div>
<!-- /#page-wrapper -->

<?php
include_once WWW_DIR.'page/template.footer.php';
?>